Changed upgrade_cmd to update_cmd - Added min python version

diff --git a/install_utils/get_install_cmd b/install_utils/get_install_cmd
--- a/install_utils/get_install_cmd
+++ b/install_utils/get_install_cmd
@@ -1,10 +1,10 @@
 #!/bin/bash
 distro=`$(dirname "${BASH_SOURCE[0]}")/get_distro`
 case $distro in
-  ubuntu|debian) cmd="sudo apt-get install" ;;
-  centos) cmd="sudo yum install" ;;
+  ubuntu|debian) cmd="sudo apt-get -y install" ;;
+# centos|centosstream) cmd="sudo yum -y install" ;;
   manjarolinux) cmd="sudo pacman --noconfirm -S" ;;
-  "") echo "could not get distro"; exit 1 ;;
-  *) echo "$distro not supported"; exit 1 ;;
+  "") echo "could not get distro" 1>&2 ;;
+  *) echo "$distro not supported" 1>&2 ;;
 esac
 echo $cmd
diff --git a/install_utils/get_update_cmd b/install_utils/get_update_cmd
--- a/install_utils/get_update_cmd
+++ b/install_utils/get_update_cmd
@@ -2,9 +2,9 @@
 distro=`$(dirname "${BASH_SOURCE[0]}")/get_distro`
 case $distro in
   ubuntu|debian) cmd="sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y" ;;
-  centos) cmd="sudo yum ???" ;;
+# centos|centosstream) cmd="sudo yum -y update" ;;
   manjarolinux) cmd="sudo rm /var/lib/pacman/db.lck >& /dev/null; sudo pacman --noconfirm -Syu" ;;
-  "") echo "could not get distro"; cmd="" ;;
-  *) echo "$distro not supported"; cmd="" ;;
+  "") echo "could not get distro" 1>&2 ;;
+  *) echo "$distro not supported" 1>&2 ;;
 esac
 echo $cmd
